### ISSUE TITLE
Edit Create Account Text Fields

### ISSUE THREAD

**Issue by theryankelly** [401ode/GreatOutdoorsRI#10]

**Comment by theryankelly** [comment]
Add Diclaimer Text to Create Account

**Comment by theryankelly** [comment]
Button and placeholder text added to https://getoutdoorsri.com/user/register.  But accordion does not work and box can't be checked.

**Comment by nickatomlin** [comment]
Changed "communication preferences" to "policy information" as desired. For future reference, make any required changes in the "Manage fields" tab.
