### ISSUE TITLE
Fix Badge Sort in Trophy Room

### ISSUE THREAD

**Issue by theryankelly** [401ode/GreatOutdoorsRI#39]
**Current:**
100MoMiles Events
Featured Water Trails
State Park Attendance
Mileage Milestones
Healthy Months
Active Holidays
Other Achievements
Walking Miles
Running Miles
Cycling Miles
Hiking Miles
Swimming Miles
Paddling Miles
Riding Miles
Geocaching Miles
Skating Miles
Rolling Miles

**New:**
GetOutdoorsRI Events
State Park Attendance
Mileage Milestones
Healthy Months
Active Holidays
Other Achievements
Walking Miles
Running Miles
Biking Miles
Hiking Miles
Swimming Miles
Paddling Miles

**Comment by theryankelly** [comment]
In addition to removing categories or renaming cycling we also need to figure out how to get badges to display in correct category

**Comment by theryankelly** [comment]
https://github.com/401ode/GetOutdoorsRI/blob/bacbf49c19eb44868d4e929c3eb85ed76a533cd2/httpdocs/sites/default/modules/mo_project/plugins/content_types/blue_mileage_pane.inc

**Comment by nickatomlin** [comment]
Fixed by commit [https://github.com/401ode/GetOutdoorsRI/commit/af872c4e9daa1a696424b75b3364b65d4c17d1f8](https://github.com/401ode/GetOutdoorsRI/commit/af872c4e9daa1a696424b75b3364b65d4c17d1f8).
