### ISSUE TITLE
Fix Criteria for Half/Marathon

### ISSUE THREAD

**Issue by theryankelly** [401ode/GreatOutdoorsRI#40]
One Time, Event, Only Running

**Comment by nickatomlin** [comment]
By my interpretation, these should be the criteria for a marathon badge. However, a ten mile run still earned me the badge. ![capture](https://cloud.githubusercontent.com/assets/13228316/15900619/19e282c6-2d6e-11e6-883b-9f981705c004.PNG)

**Comment by nickatomlin** [comment]
Fixed the bug, but introduced the constraint that the user must log _exactly_ 13.1/26.2 miles to earn a marathon badge. Recording the nearest round-up integer, in this case 14 or 27, also awards a marathon badge.

Single mileage log now works as expected, so someone who records two runs of 13.1 miles will only earn the half-marathon badge. Similarly, if the user records a 13 mile run and then a 14 mile run, only the second run will award a badge (and it will award only the half-marathon badge).
