### ISSUE TITLE
Remove "Latest" option from Tagboard Embed

### ISSUE THREAD

**Issue by theryankelly** [401ode/GreatOutdoorsRI#45]
https://github.com/401ode/GreatOutdoorsRI/blob/master/httpdocs/sites/all/modules/mogov/mo_cms_tagboard/mo_cms_tagboard.module

**Comment by nickatomlin** [comment]
I have posted a question on Basecamp about this and am awaiting a response.

**Comment by nickatomlin** [comment]
Commit  b4c5755 fixes this issue. The 'latest' tab was added in 8719eff044c035fb405bf992c393838f6966ebcd which is reverted in this commit.
