### ISSUE TITLE
Fix Trophy Room Error

### ISSUE THREAD

**Issue by theryankelly** [401ode/GreatOutdoorsRI#47]
Warning: key() expects parameter 1 to be array, string given in mo_project_badge_gallery_sort() (line 731 of /home/drupal/GoRI/httpdocs/sites/default/modules/mo_project/includes/badges.inc).
Notice: Trying to get property of non-object in mo_project_build_badge_archive_helper() (line 711 of /home/drupal/GoRI/httpdocs/sites/default/modules/mo_project/includes/badges.inc).
Warning: key() expects parameter 1 to be array, string given in mo_project_badge_gallery_sort() (line 731 of /home/drupal/GoRI/httpdocs/sites/default/modules/mo_project/includes/badges.inc).
Notice: Trying to get property of non-object in mo_project_build_badge_archive_helper() (line 711 of /home/drupal/GoRI/httpdocs/sites/default/modules/mo_project/includes/badges.inc).

**Comment by theryankelly** [comment]
Related to #39

**Comment by nickatomlin** [comment]
Fixed by commit [af872c4](https://github.com/401ode/GetOutdoorsRI/commit/af872c4e9daa1a696424b75b3364b65d4c17d1f8), which reverts to the old code and removes the key() function.
